on:
  release:
    types: [published]
name: upload-release-assets
jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - name: 'Cache node_modules'
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            package-lock.json
          key: ${{ runner.os }}-node-v16-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v16-
      - name: Install Dependencies
        run: npm install
      - name: Run Build
        run: npm run release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./DemoMonkey-${{ github.event.release.tag_name }}-stable.zip
          asset_name: DemoMonkey-${{ github.event.release.tag_name }}-stable.zip
          asset_content_type: application/zip